### ISSUE TITLE
No option  to copy firmware to initramfs

### ISSUE THREAD

**Issue by mykhaylo-** [fearedbliss/bliss-initramfs#4]
Hi,
Recently i got an issue that *iwlwifi* kernel module wasn't picked up during bootup because firmware wasn't found. After a bit of investigation I realized that at the moment kernel boots from initram, there is no firmware files because */lib/firmware* doesn't exist in initramfs. From the source code I see that there should be a possibility to copy firmware to initramfs but I can't figure out how to do this. *bliss-initramfs* simply asks me two questions - first is which initramfs I want and second  - which kernel version to use. and based on that it generates initramfs image. And there is no option to select that I want to add firmware to the initramfs. 
Please suggest what to do here.

**Comment by fearedbliss** [comment]
Hey, you need to modify the /opt/bliss-initramfs/pkg/hooks/Firmware.py file
and enable it. Also add your firmware to the list.

However, you don't need to do this for your case because it isn't the
responsibility of the initramfs to load that firmware that early for what
you want. You are simply just missing the firmware in the first place (I
also have an Intel wireless card).

Install the linux-firmware package in Gentoo and reboot.

**Comment by mykhaylo-** [comment]
Thanks for quick response. 
It wasn't mentioned in any documentation or readme, that's why I was a bit confused. Now I got it, thanks. Would be great if you highlight this point with editing *Firmware.py* somewhere in readme, so that others will be aware of that. Issue was that kernel tried to load the *iwlwifi* module and haven't found required firmware file under */lib/firmware* because it happened before switching root and only what was included in initramfs was available. And since */lib/firmware* wasn't included, module loading had failed with error that firmware cannot be found.

Does it make sense to refactor implementation in a way which doesn't require any editing of */opt/bliss-initramfs/...* ? For example by introducing some configuration file *bliss-initramfs.conf* in /etc which will contain all required configuration: which initramfs I want to build, whether include or not include firmware, if include then all files or only those which I specify in conf file, also any other settings which you see make sense to make configurable. How does it sound for you?

**Comment by fearedbliss** [comment]
That would require code changes to do and I don't really think this is an issue.

For the firmware documentation, when you have time, can you take a look at the /usr/share/doc/bliss-initramfs-6.1.4/USAGE.bz2 ? I introduced firmware support in 6.0.0 but I guess I forgot to add documentation. If you add it in there, send me a pull request :).

Also, like I said before, your module was attempted to be loaded and failed, but it wasn't because of the initramfs. I also have a 'iwlwifi' card and what you need to do is install the 'linux-firmware' package and when OpenRC starts, the module will load and use your firmware from within your real rootfs. You don't need to have it in the initramfs at that point (also you would only want to include this firmware if you were planning on having network support inside of the initramfs).

**Comment by mykhaylo-** [comment]
ok. thank you.
I've just created pull request which includes this missing information about firmware.

**Comment by mykhaylo-** [comment]
And how to you feel about creating a configuration file which will be stored in /etc rather than directly editing files in installation directory?

**Comment by fearedbliss** [comment]
I thought about this a few years ago and decided not to do it. Reason is that the use case I'm looking at is that people will usually be remaking their initramfs for different kernels and it could be for different options. It could be annoying having to go into a configuration file to do this when you could just do:

bliss-initramfs 2 3.19.3-FC.01

and then have the initramfs automatically make a Encrypted ZFS initramfs for that specific kernel. 

Since your main issue is solved, I'll be closing this :).
